### ISSUE TITLE
NVidia TX1

### ISSUE THREAD

**Issue by jbcpollak** [resin-os/resin-os-device-support#45]
It would be great if Resio.io supported the TX1:

* **CPU**:  64-bit ARM® A57 CPUs
* **GPU**: 256-core NVIDIA
* **Memory**: 4GB
* **Storage**: 16GB eMMC, also SATA interface

* **Link**: http://www.nvidia.com/object/jetson-tx1-module.html

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_18f5)

**Comment by mr337** [comment]
TX2 is now released also, https://developer.nvidia.com/embedded/buy/jetson-tx2.

**Comment by mr337** [comment]
Also looks like there is a BSP layer, not 100% sure if its official. 
https://github.com/madisongh/meta-tegra

I have hardware of TX1 and TX2.

**Comment by shaunmulligan** [comment]
@jbcpollak and @mr337 we actually just started work on supporting the TX1 and the TX2 will follow shortly after that, so keep an eye out for it in the next month or so.

**Comment by kgreenek** [comment]
Any updates on this? I've been following this thread eagerly. At my company, our platform is based on the TX1 (soon to move to the TX2). We would LOVE to be able to deploy using resin / docker. We still need to be able to leverage the full power of the GPU though.

**Comment by mr337** [comment]
Hope its coming down soon. I too need full access to GPU (one of the reason to go TX1/TX2). From all my previous conversations the entire hardware is accessible from inside a container.

**Comment by jd20** [comment]
I see TX2 is now supported, is the TX1 still on the roadmap too?

**Comment by mr337** [comment]
@jd20 My hunch is if they haven't supported TX1 yet, they probably won't since it is yesterdays technology. I am hoping that I am wrong, but just my two cents.

Aside from cost to upgrade, is there anything preventing to upgrade to the TX2? It is well worth the upgrade IMO.

**Comment by telphan** [comment]
@mr337 @jd20 We do plan on releasing the TX1, unfortunately the TX2 work revealed a few problems with the tegra boards which blocked the release of the TX1. But we have a complete PR now to support it and should we released shortly.
https://github.com/resin-os/resin-jetson-tx1/pull/1

**Comment by jd20** [comment]
@telphan Cool, that's great to hear.

**Comment by alisondavis17** [comment]
Hi all, we've just released beta support for the TX1!

**Comment by telphan** [comment]
This is fully supported now. Closing the ticket.
