### ISSUE TITLE
NVIDIA TX2

### ISSUE THREAD

**Issue by telphan** [resin-os/resin-os-device-support#53]
* **CPU**:  
HMP Dual Denver 2/2 MB L2 + 
Quad ARM® A57/2 MB L2
* **GPU**:
NVIDIA Pascal™, 256 CUDA cores
* **Memory**:
8 GB 128 bit LPDDR4
59.7 GB/s
* **Storage**:
32 GB eMMC, SDIO, SATA

* **Link**:
https://developer.nvidia.com/embedded/buy/jetson-tx2

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2bw3)

**Comment by dborgesr** [comment]
+1 will have hardware soon

**Comment by kgreenek** [comment]
Major +1 for supporting the tx2. At area17 we are eagerly awaiting this so we can try out resin

**Comment by agherzan** [comment]
Resin support for this board was released in production.
